<?xml version="1.0"?>
<robot name="ddbot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- lidar -->
  <xacro:property name="lidar_radius" value="0.03685"/>
  <xacro:property name="lidar_length" value="0.0425"/>

  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
      </geometry>
    </collision>

    <xacro:cylinder_inertia m="0.5" r="${lidar_radius}" h="${lidar_length}"/>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="body_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${(base_height/2+lidar_length/2)}" rpy="0 0 0"/>
  </joint>

</robot>